config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users

  resources :users, except: %i(new create)

  resources :musics, controller: :medias do
    post :favorite
    post :purchase
  end

  resources :podcasts, controller: :medias do
    post :favorite
    post :purchase
  end

  resources :videos, controller: :medias do
    post :favorite
    post :purchase
  end

  resources :books, controller: :medias do
    post :favorite
    post :purchase
  end

  get :favorites, to: 'favorites#index'

  resources :credits, only: %i(index new create)

  get :dashboard, to: 'pages#dashboard'
  root to: redirect('/musics')
end

app/models/media.rb
class Media < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :user_id, touch: true

  validates :name, :description, :image, :price, :author, :category, :type, presence: true

  validates :price, numericality: { greater_than_or_equal_to: 0.01 }

  validates :size, presence: true, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 1,
  }

  def disable(reason)
    self.removed = true
    self.published = false
    self.deleted_at = Time.now
    self.deleted_reason = reason
    save
  end
end

app/controllers/medias_controller.rb
class MediasController < ApplicationController
  before_action :detect_media_type
  before_action :set_media, only: [:show, :edit, :update, :destroy, :favorite, :purchase]

  def index
    authorize(Media)
    @media = @type.all
    render "#{@kind}/index"
  end

  # GET /media/1
  # GET /media/1.json
  def show
    authorize(@media.becomes(Media))
  end


  def new
    @media = @type.new
    authorize(@media.becomes(Media))
  end

  def edit
    authorize(@media.becomes(Media))
  end

  def create
    @media = @type.new(media_params)
    @media.author = current_user
    authorize(@media.becomes(Media))

    respond_to do |format|
      if @media.save
        format.html { redirect_to @media, notice: 'Media was successfully created.' }
        format.json { render :show, status: :created, location: @media }
      else
        format.html { render :new }
        format.json { render json: @media.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /media/1
  # PATCH/PUT /media/1.json
  def update
    authorize(@media.becomes(Media))
    respond_to do |format|
      if @media.update(media_params)
        format.html { redirect_to @media, notice: 'Media was successfully updated.' }
        format.json { render :show, status: :ok, location: @media }
      else
        format.html { render :edit }
        format.json { render json: @media.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /media/1
  # DELETE /media/1.json
  def destroy
    authorize(@media.becomes(Media))
    @media.disable("Removido")
    respond_to do |format|
      format.html { redirect_to media_index_url, notice: 'Media was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def favorite
    authorize(@media)
    existing = current_user.favorites.where(media: @media).destroy_all
    if existing.empty?
      current_user.favorites.create(media: @media)
    end
    respond_to do |format|
      format.html { redirect_back(fallback_location: root_path) }
      format.json { render nothing: true, status: :created }
    end
  end

  def purchase
    authorize(@media)
    pr = current_user.purchases.create(media: @media, price: @media.price)
    if
      redirect_to @media, notice: 'Success'
    else
      redirect_back fallback_location: @media, notice: 'Failure'
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_media
    @media = @type.find(params[:id] || params["#{@param_key}_id"])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def media_params
    params.require(@param_key).permit(:name, :description, :image, :price, :author, :category, :size)
  end

  def detect_media_type
    @kind = request.path.match(/^\/([^\/]+)/).captures.first
    @param_key = @kind.singularize
    @type = @param_key.classify.constantize
  end
end

app/helpers/medias_helper.rb
module MediasHelper
end

app/views/medias/_form.html.erb
<%= simple_form_for(media) do |f| %>
  <% if media.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(media.errors.count, "error") %> prohibited this media from being saved:</h2>

      <ul>
      <% media.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :image %>
    <%= f.input :category, collection: @type::CATEGORIES %>
    <%= f.input :price %>
    <%= f.input :size %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/medias/edit.html.erb
<h1>Editing Media</h1>

<%= render 'form', media: @media %>

<%= link_to 'Show', @media %>

app/views/medias/new.html.erb
<h1>New <%= @type %></h1>

<%= render 'form', media: @media %>

<%= link_to 'Back', @type %>

app/views/medias/show.html.erb
Name: <%= @media.name %> <br>
Description: <%= @media.description %> <br>
Image: <%= image_tag @media.image %> <br>
Price: <%= number_to_currency @media.price %> <br>
Author: <%= link_to @media.author.full_name, user_path(@media.author) %> <br>
Category: <%= @media.category %> <br>
<%= @media.human_size %>

<hr>
<p>Purchase? <%= current_user.purchases.exists?(media: @media) ? 'Yes' : 'No' %></p>

<hr>
<% if policy(@media).edit? %>
  <%= link_to 'Edit', [:edit, @media] %>
  <br>
<% end %>
<%= link_to 'Back', @type %>