config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users

  resources :users, except: %i(new create)

  resources :musics, controller: :medias do
    post :favorite
    post :purchase
  end

  resources :podcasts, controller: :medias do
    post :favorite
    post :purchase
  end

  resources :videos, controller: :medias do
    post :favorite
    post :purchase
  end

  resources :books, controller: :medias do
    post :favorite
    post :purchase
  end

  get :favorites, to: 'favorites#index'

  resources :credits, only: %i(index new create)

  get :dashboard, to: 'pages#dashboard'
  root to: redirect('/musics')
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :medias, dependent: :nullify
  has_many :purchases, dependent: :nullify
  has_many :favorites, dependent: :destroy
  has_many :credits, dependent: :nullify

  validates :first_name, :last_name, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end

  def desactive
    update(active: false)
  end

  def credits_amount
    credits.sum(:amount)
  end

  def active_for_authentication?
    super && active?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
    authorize(User)
  end

  def show
    authorize(@user)
  end

  def edit
    authorize(@user)
  end

  def update
    authorize(@user)

    if (user_params[:password] != user_params[:password_confirmation]) || user_params[:password].blank? || user_params[:password_confirmation].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end

    if @user.update(user_params)
      redirect_to user_path(@user), notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    authorize(@user)
    @user.desactive
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :type)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= simple_form_for(user.becomes(User), url: user_path(user), as: :user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.input :email %>
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :password %>
    <%= f.input :password_confirmation %>
    <%= f.input :type, collection: [Academic, Author, Admin], allow_blank: false %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="6"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.full_name %></td>
        <td><%= user.type %></td>
        <td><%= user.active? ? 'Active' : 'Removed' %></td>
        <td><%= link_to 'Show', user_path(user) %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p>Name: <%= @user.full_name %></p>
<p>Email: <%= @user.email %></p>
<p>Created at: <%= l @user.created_at %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>