config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users

  resources :users, except: %i(new create)

  resources :musics, controller: :medias do
    post :favorite
    post :purchase
  end

  resources :podcasts, controller: :medias do
    post :favorite
    post :purchase
  end

  resources :videos, controller: :medias do
    post :favorite
    post :purchase
  end

  resources :books, controller: :medias do
    post :favorite
    post :purchase
  end

  get :favorites, to: 'favorites#index'

  resources :credits, only: %i(index new create)

  get :dashboard, to: 'pages#dashboard'
  root to: redirect('/musics')
end

app/models/academic.rb
class Academic < User
  after_touch :check_if_have_published_media

  private

  def check_if_have_published_media
    update_column(:type, Author) if medias.exists?
  end
end

app/models/admin.rb
class Admin < User
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < User
  after_touch :check_if_have_published_media

  private

  def check_if_have_published_media
    update_column(:type, Academic) if medias.count.zero?
  end
end

app/models/book.rb
class Book < Media
  CATEGORIES = [
    "Arts & Entertainment",
    "Bopgraphies & Memoirs",
    "Books in Spanish",
    "Business & Personal Finance",
    "Children & Teens",
    "Comics & Graphic Novels",
    "Computers & Internet",
    "Cookbooks, Food & Wine",
    "Education",
    "Fiction & Literature",
    "Health, Mind & Body",
    "History",
    "Humor",
    "Lifestyle & Home",
    "Mysteries & Thrillers",
    "Nonfiction",
    "Parenting",
    "Politics & Current Events",
    "Professional & Technical",
    "Reference",
    "Religion & Spirituality",
    "Romance",
    "Sci-Fy & Fantasy",
    "Science & Nature",
    "Sports & Outdoors",
    "Textbooks",
    "Travel & Adventure",
  ]

  def human_size
    "#{size} páginas"
  end
end

app/models/credit.rb
class Credit < ApplicationRecord
  belongs_to :user
  belongs_to :purchase

  validates :user, :amount, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :media

  validates :user_id, uniqueness: { scope: :media_id }
end

app/models/media.rb
class Media < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :user_id, touch: true

  validates :name, :description, :image, :price, :author, :category, :type, presence: true

  validates :price, numericality: { greater_than_or_equal_to: 0.01 }

  validates :size, presence: true, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 1,
  }

  def disable(reason)
    self.removed = true
    self.published = false
    self.deleted_at = Time.now
    self.deleted_reason = reason
    save
  end
end

app/models/music.rb
class Music < Media
  CATEGORIES = [
    "Alternative",
    "Blues",
    "Children's Music",
    "Christian & Gospel",
    "Classical",
    "Comedy",
    "Country",
    "Dance",
    "Eletronic",
    "Fitness & Workout",
    "Hip-Hop/Rap",
    "New Artists",
    "Jazz",
    "Latino",
    "Live Music",
    "Metal",
    "Classical Hits",
    "Pop",
    "R&B/Soul",
    "Reggae",
    "Rock",
    "Singer/Songwritter",
    "Soundtrack",
    "World",
  ]

  def human_size
    "#{size} minutos"
  end
end

app/models/podcast.rb
class Podcast < Media
  CATEGORIES = [
    "Arts",
    "Business",
    "Comedy",
    "Education",
    "Games & Hobbies",
    "Government & Organizations",
    "Health",
    "Kids & Family",
    "Music",
    "News & Politics",
    "Religion & Spirituality",
    "Science & Medicine",
    "Society & Culture",
    "Sports & Recreation",
    "Technology",
    "TV & Film",
  ]

  def human_size
    "#{size} minutos"
  end
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  before_create :discount_credits

  belongs_to :user
  belongs_to :media

  validates :user, :media, presence: true

  validates :price, presence: true, numericality: {
    greater_than_or_equal_to: 0.01,
  }

  validate :user_have_credits

  private

  def user_have_credits
    user.credits_amount >= media.price
  end

  def discount_credits
    user.credits.create(amount: media.price * -1.0)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :medias, dependent: :nullify
  has_many :purchases, dependent: :nullify
  has_many :favorites, dependent: :destroy
  has_many :credits, dependent: :nullify

  validates :first_name, :last_name, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end

  def desactive
    update(active: false)
  end

  def credits_amount
    credits.sum(:amount)
  end

  def active_for_authentication?
    super && active?
  end
end

app/models/video.rb
class Video < Media
  CATEGORIES = [
    "Kids & Family",
    "Comedy",
    "Action & Adventure",
    "Classics",
    "Documentary",
    "Drame",
    "Foreign",
    "Horror",
    "Independent",
    "Music",
    "Romance",
    "Sci-Fi & Fantasy",
    "Short Films",
    "Sports",
    "Thriller",
    "Western",
  ]

  def human_size
    "#{size} minutos"
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def dashboard
    @purchases = Credit.where('"credits"."amount" > 0').all
    authorize(:dashboard)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
    authorize(User)
  end

  def show
    authorize(@user)
  end

  def edit
    authorize(@user)
  end

  def update
    authorize(@user)

    if (user_params[:password] != user_params[:password_confirmation]) || user_params[:password].blank? || user_params[:password_confirmation].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end

    if @user.update(user_params)
      redirect_to user_path(@user), notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    authorize(@user)
    @user.desactive
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :type)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/credits_helper.rb
module CreditsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/medias_helper.rb
module MediasHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
<div>
  <%= book.name %><br>
  <%= book.human_size %>
  <%= image_tag book.image %>
  <% if policy(book).favorite? %>
    <%= link_to "Fav", [book, :favorite], method: :post %>
  <% end %>
  <% if policy(book).purchase? %>
    <%= link_to "Buy", [book, :purchase], method: :post %>
  <% end %>
  <% if policy(book).destroy? %>
    <%= link_to "Remove", book, method: :delete %>
  <% end %>
</div>

app/views/books/index.html.erb
<h1>Somente Livros</h1>

<div>
  <% @media.each do |media| %>
    <%= render media %>
  <% end %>
</div>

<br>

<%= link_to "New Book", new_book_path %>

app/views/musics/_music.html.erb
<div>
  <%= music.name %><br>
  Duração: <%= music.human_size %>
  <%= image_tag music.image %>
  <% if policy(music).favorite? %>
    <%= link_to "Fav", [music, :favorite], method: :post %>
  <% end %>
  <% if policy(music).purchase? %>
    <%= link_to "Buy", [music, :purchase], method: :post %>
  <% end %>
  <% if policy(music).destroy? %>
    <%= link_to "Remove", music, method: :delete %>
  <% end %>
</div>

app/views/musics/index.html.erb
<h1>Somente Músicas</h1>

<div>
  <% @media.each do |media| %>
    <%= render media %>
  <% end %>
</div>

<br>

<%= link_to "New Music", new_music_path %>

app/views/podcasts/_podcast.html.erb
<div>
  <%= podcast.name %><br>
  Duração: <%= podcast.human_size %>
  <%= image_tag podcast.image %>
  <% if policy(podcast).favorite? %>
    <%= link_to "Fav", [podcast, :favorite], method: :post %>
  <% end %>
  <% if policy(podcast).purchase? %>
    <%= link_to "Buy", [podcast, :purchase], method: :post %>
  <% end %>
  <% if policy(podcast).destroy? %>
    <%= link_to "Remove", podcast, method: :delete %>
  <% end %>
</div>

app/views/podcasts/index.html.erb
<h1>Somente Podcasts</h1>

<div>
  <% @media.each do |media| %>
    <%= render media %>
  <% end %>
</div>

<br>

<%= link_to "New Podcast", new_podcast_path %>

app/views/videos/_video.html.erb
<div>
<%= link_to video.name, video %><br>
Duração: <%= video.human_size %>
<%= image_tag video.image %>
<% if policy(video).favorite? %>
  <%= link_to "Fav", [video, :favorite], method: :post %>
<% end %>
<% if policy(video).purchase? %>
  <%= link_to "Buy", [video, :purchase], method: :post %>
<% end %>
<% if policy(video).destroy? %>
  <%= link_to "Remove", video, method: :delete %>
<% end %>
</div>

app/views/videos/index.html.erb
<h1>Somente Vídeos</h1>

<div>
  <% @media.each do |media| %>
    <%= render media %>
  <% end %>
</div>

<br>

<%= link_to "New Video", new_video_path %>