config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users

  resources :users, except: %i(new create)

  resources :musics, controller: :medias do
    post :favorite
    post :purchase
  end

  resources :podcasts, controller: :medias do
    post :favorite
    post :purchase
  end

  resources :videos, controller: :medias do
    post :favorite
    post :purchase
  end

  resources :books, controller: :medias do
    post :favorite
    post :purchase
  end

  get :favorites, to: 'favorites#index'

  resources :credits, only: %i(index new create)

  get :dashboard, to: 'pages#dashboard'
  root to: redirect('/musics')
end

app/models/credit.rb
class Credit < ApplicationRecord
  belongs_to :user
  belongs_to :purchase

  validates :user, :amount, presence: true
end

app/controllers/credits_controller.rb
class CreditsController < ApplicationController
  def index
    authorize(Credit)
    @credits = current_user.credits
  end

  def new
    authorize(:credit)
    @credit = PaymentForm.new()
  end

  def create
    payment = SomeMagicClassOfPayment.new(params: credit_params, user: current_user)
    authorize(:credit)
    if payment.create
      redirect_to credits_path, notice: 'Success'
    else
      render :new, notice: 'Failure'
    end
  end

  private

  def credit_params
    params.require(:credit).permit(:amount)
  end
end

app/helpers/credits_helper.rb
module CreditsHelper
end

app/views/credits/index.html.erb
<h1>Credits</h1>

<% if policy(:credit).new? %><%= link_to 'Add credits', new_credit_path %><% end %>

<% @credits.find_each do |credit| %>
  <div style="background: <%= credit.amount < 0 ? 'red' : 'green' %>">
    <%= credit.amount < 0 ? '-' : '+'%><%= number_to_currency credit.amount %>
  </div>
<% end %>

app/views/credits/new.html.erb
<%= simple_form_for @credit, url: credits_path do |f| %>
  <%= f.input :amount %>
  <%= f.input :type, collection: ['Credit card', 'Bank slip', 'Deposit'], include_blank: false, as: :radio_buttons %>
  <div id="creditcard-fields">
  </div>
  <%= f.submit %>
<% end %>